import { Captions, Sparkles } from 'lucide-react';

export type KeyKind = 'subdl' | 'gemini';

// One place to say what each integration is, why it needs a key of yours and what
// you lose without it. Shared by the welcome flow (which shows `short` beside the
// field), the watch-page subtitle notice and the missing-key dialog (which show
// `why` + `without`), so the same feature is never explained two different ways.
// Every line is one sentence on purpose — these sit in dialogs and forms, not on
// a docs page.
export const KEY_COPY = {
  subdl: {
    icon: Captions,
    provider: 'SubDL',
    feature: 'Subtitles',
    short: 'Captions for any title + clickable Learn-English mode.',
    why: '9film has no subtitle account of its own, so subtitles stay off until you add your own SubDL key.',
    without: 'Playback, your list and watch progress are unaffected.',
    href: 'https://subdl.com/panel/api',
    linkLabel: 'Get a free key',
  },
  gemini: {
    icon: Sparkles,
    provider: 'Gemini',
    feature: 'Smarter learning',
    short: 'Idiom & phrase breakdowns, plus AI-graded meaning tests.',
    why: 'Phrase breakdowns are generated by Gemini, and this app has no key of its own.',
    without: 'Without one a phrase falls back to a plain translation.',
    href: 'https://aistudio.google.com/app/apikey',
    linkLabel: 'Get a free key',
  },
} as const satisfies Record<KeyKind, unknown>;
