import { useNavigate } from 'react-router-dom';
import { Captions, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import type { KeyKind } from '@/hooks/use-missing-key';

const COPY = {
  subdl: {
    icon: Captions,
    title: 'Subtitles need a SubDL key',
    description:
      "This app has no subtitle account of its own, so there are no subtitles to show until you add your own SubDL API key.",
    detail: 'Everything else — playback, your list, watch progress — works without it.',
    href: 'https://subdl.com/panel/api',
    linkLabel: 'Get a free SubDL key',
  },
  gemini: {
    icon: Sparkles,
    title: 'AI explanations need a Gemini key',
    description:
      'Idiom and phrase breakdowns are generated by Gemini, and this app has no key of its own. Without one you still get a plain translation of the phrase.',
    detail: 'Dictionary lookups, saving words and self-tests all work without it.',
    href: 'https://aistudio.google.com/app/apikey',
    linkLabel: 'Get a Gemini key',
  },
} as const satisfies Record<KeyKind, unknown>;

interface MissingKeyDialogProps {
  kind: KeyKind;
  open: boolean;
  onClose: () => void;
}

// Shown the first time in a session that a feature is used whose API key isn't
// set. Both integrations are optional, so this only ever informs and offers a
// shortcut to Connections — dismissing it leaves the feature off, not broken.
export function MissingKeyDialog({ kind, open, onClose }: MissingKeyDialogProps) {
  const navigate = useNavigate();
  const copy = COPY[kind];
  const Icon = copy.icon;

  return (
    <Dialog open={open} onOpenChange={(o) => !o && onClose()}>
      <DialogContent>
        <DialogTitle>{copy.title}</DialogTitle>
        <DialogDescription>{copy.description}</DialogDescription>

        <div className="mt-4 flex items-start gap-3 rounded-xl border border-white/10 bg-white/[0.03] p-3">
          <Icon className="w-5 h-5 text-orange-400 shrink-0 mt-0.5" />
          <p className="text-sm text-zinc-300">
            {copy.detail}{' '}
            <a
              href={copy.href}
              target="_blank"
              rel="noreferrer"
              className="text-orange-400 hover:text-orange-300 underline underline-offset-2"
            >
              {copy.linkLabel}
            </a>
            , then paste it into Profile → Connections.
          </p>
        </div>

        <div className="mt-6 flex justify-end gap-3">
          <Button variant="ghost" size="sm" className="rounded-lg" onClick={onClose}>
            Not now
          </Button>
          <Button
            variant="primary"
            size="sm"
            className="rounded-lg"
            onClick={() => {
              onClose();
              navigate('/profile');
            }}
          >
            Add key
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
